// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYSube8yo-508roaceL70IskGGvb9GILY',
    appId: '1:601052336382:web:4a9c5be13ff12da18d15af',
    messagingSenderId: '601052336382',
    projectId: 'login1-ccf75',
    authDomain: 'login1-ccf75.firebaseapp.com',
    storageBucket: 'login1-ccf75.firebasestorage.app',
    measurementId: 'G-Y5Y3B4Z856',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0JYm3_BEVoNcmIx_UN1WPoiXnzehqPg',
    appId: '1:601052336382:android:8caabab3816a38898d15af',
    messagingSenderId: '601052336382',
    projectId: 'login1-ccf75',
    storageBucket: 'login1-ccf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8-5CN3hJVKxldsAQ_srhfQLP8mpN2Ls',
    appId: '1:601052336382:ios:60e4bb5957ab94b08d15af',
    messagingSenderId: '601052336382',
    projectId: 'login1-ccf75',
    storageBucket: 'login1-ccf75.firebasestorage.app',
    iosBundleId: 'com.example.login1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8-5CN3hJVKxldsAQ_srhfQLP8mpN2Ls',
    appId: '1:601052336382:ios:60e4bb5957ab94b08d15af',
    messagingSenderId: '601052336382',
    projectId: 'login1-ccf75',
    storageBucket: 'login1-ccf75.firebasestorage.app',
    iosBundleId: 'com.example.login1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYSube8yo-508roaceL70IskGGvb9GILY',
    appId: '1:601052336382:web:5c4315976cea72708d15af',
    messagingSenderId: '601052336382',
    projectId: 'login1-ccf75',
    authDomain: 'login1-ccf75.firebaseapp.com',
    storageBucket: 'login1-ccf75.firebasestorage.app',
    measurementId: 'G-JFRMH5B76Y',
  );
}
